version: '2'

services:
  elasticsearch:
    image: elasticsearch
    volumes:
      - './elastic/config:/usr/share/elasticsearch/config'
    ports:
      - '9200'
      - '9300'

  kibana:
    image: kibana
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'

  head:
    image: mobz/elasticsearch-head:5
    ports:
      - '9100:9100'
