version: '2'

services:
  elasticsearch:
    build: ./elastic
    ports:
      - '9200'
      - '9300'

  kibana:
    build: ./kibana
    depends_on: 
      - elasticsearch
    ports: 
      - '5601:5601'

# TODO: Enable http.cors.enabled: true and http.cors.allow-origin: "*" in es
#  head:
#    image: mobz/elasticsearch-head:5
#    ports:
#      - '9100:9100'
   